# Generated by Django 6.0.7 on 2026-07-30 20:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='follow',
            name='last_viewed_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
