# Generated by Django 6.0.7 on 2026-07-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='edited_count',
            field=models.IntegerField(default=0),
        ),
    ]
